name: Main

on:
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: umidbekk/actions/prepare-node-repo@v2
        with:
          cache-key: yarn-v4

      - run: yarn check:types
      - run: yarn lint
      - run: yarn test
      - uses: codecov/codecov-action@v2.1.0
      - run: yarn build

  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: umidbekk/actions/prepare-node-repo@v2
        with:
          cache-key: yarn-v4

      - run: yarn docs
      - id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          channelId: live
          target: superdispatch-ui
          projectId: ${{ secrets.FIREBASE_PROJECT }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_HOSTING_SERVICE_ACCOUNT_JSON }}

  e2e:
    needs:
      - checks
      - docs
    runs-on: ubuntu-latest
    steps:
      - uses: umidbekk/actions/prepare-node-repo@v2
        with:
          cache-key: yarn-v4
      - run: yarn cypress install
      - run: yarn cypress run
        env:
          CYPRESS_HOST: https://ui.superdispatch.org

  visual-testing:
    needs:
      - checks
      - docs
    runs-on: ubuntu-latest
    steps:
      - uses: umidbekk/actions/prepare-node-repo@v2
        with:
          cache-key: yarn-v4
      - run: yarn test-visual-ci https://ui.superdispatch.org
