name: PR Workflow
on:
  pull_request:
    branches:
      - master
    paths:
      - packages/ui/**

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: superdispatch/actions/prepare-node-repo@v2
        with:
          cache-key: cache-v6-
          pnpm-version: 10
          fetch-depth: 2
      - run: git fetch origin master --depth=1
      - run: npx nx affected --target=lint --base=origin/master
      - run: npx nx affected --target=test --base=origin/master

  build-storybook:
    runs-on: ubuntu-latest
    needs:
      - checks
    steps:
      - uses: superdispatch/actions/prepare-node-repo@v2
        with:
          cache-key: cache-v6-
          pnpm-version: 10
      - run: npx nx build-storybook @superdispatch/ui-next --verbose
      - uses: actions/upload-artifact@v4
        with:
          name: storybook-build
          path: packages/ui/storybook-static

  deploy:
    runs-on: ubuntu-latest
    environment: Testing
    needs:
      - build-storybook
      - checks
    outputs:
      superdispatch-ui-next-preview-url: ${{ steps.deploy-url.outputs.superdispatch-ui-next }}

    steps:
      - uses: superdispatch/actions/prepare-node-repo@v2
        with:
          cache-key: cache-v4-
          pnpm-version: 10

      - uses: actions/download-artifact@v4
        with:
          name: storybook-build
          path: packages/ui/storybook-static

      - id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          expires: 3d
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          projectId: ${{ secrets.FIREBASE_PROJECT }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_HOSTING_SERVICE_ACCOUNT_JSON }}

      - id: deploy-url
        run: echo "superdispatch-ui-next=${{ steps.deploy.outputs.details_url }}" >> $GITHUB_OUTPUT
