name: PR

on:
  pull_request_target:
    types: [labeled]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: umidbekk/actions/npm/install@v1
      - run: yarn check:types
      - run: yarn lint
      - run: yarn test
      - uses: codecov/codecov-action@v2.0.2

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: umidbekk/actions/npm/install@v1
      - uses: superdispatch/actions/build-size/limit@v1
        with:
          install_command: 'yarn install'
          build_command: 'yarn build'

  preview:
    runs-on: ubuntu-latest

    outputs:
      deploy-url: ${{ steps.deploy.outputs.details_url }}

    steps:
      - uses: actions/checkout@v2
      - uses: umidbekk/actions/npm/install@v1
      - run: yarn storybook:build
      - run: yarn playroom:build
      - id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          target: superdispatch-ui
          channelId: ${{ github.event.number }}
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          projectId: ${{ secrets.FIREBASE_PROJECT }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_HOSTING_SERVICE_ACCOUNT_JSON }}

  e2e:
    needs:
      - checks
      - preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: umidbekk/actions/npm/install@v1
      - run: yarn cypress install
      - run: yarn percy exec -- cypress run
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          CYPRESS_HOST: ${{ needs.preview.outputs.deploy-url }}
