name: Publish web-ui

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version bump type"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: superdispatch/actions/prepare-node-repo@v2
        with:
          cache-key: cache-v6-
          pnpm-version: 10

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Configure npm for GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
          echo "@superdispatch:registry=https://npm.pkg.github.com" >> ~/.npmrc

      - name: Bump version (if manual trigger)
        if: github.event_name == 'workflow_dispatch'
        working-directory: packages/ui
        run: |
          pnpm version ${{ inputs.version }} --no-git-tag-version
          VERSION=$(node -p "require('./package.json').version")
          echo "NEW_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Get current version
        if: github.event_name == 'push'
        working-directory: packages/ui
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "NEW_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check if version already published
        id: check-version
        working-directory: packages/ui
        continue-on-error: true
        run: |
          if npm view @superdispatch/ui-next@${{ env.NEW_VERSION }} version 2>/dev/null; then
            echo "already_published=true" >> $GITHUB_OUTPUT
          else
            echo "already_published=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish to GitHub Packages
        if: steps.check-version.outputs.already_published != 'true'
        working-directory: packages/ui
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit version bump
        if: github.event_name == 'workflow_dispatch' && steps.check-version.outputs.already_published != 'true'
        run: |
          git add packages/ui/package.json
          git commit -m "chore(ui): bump version to ${{ env.NEW_VERSION }}"
          git push

      - name: Create Git tag
        if: steps.check-version.outputs.already_published != 'true'
        run: |
          git tag "ui-v${{ env.NEW_VERSION }}"
          git push origin "ui-v${{ env.NEW_VERSION }}"

      - name: Skip - Version already published
        if: steps.check-version.outputs.already_published == 'true'
        run: echo "Version ${{ env.NEW_VERSION }} is already published. Skipping publish step."
